### ISSUE TITLE
Toolbox requirements: Video_and_Image_Blockset

### ISSUE THREAD

**Issue by cachitas** [maljoras/xyTracker#11]
I was giving a try to your tracker and got this error:

```
Error using vision.Autothresholder
License checkout failed.
License Manager Error -10
Your license for Video_and_Image_Blockset has expired.
```

From the docs I assumed only the image processing toolbox was required, and I have it 

```
Image Processing Toolbox                              Version 9.4         (R2016a)
```

What am I missing?

**Comment by maljoras** [comment]
Hi:
Thanks for the interest in the xyTracker.  There are basically 3 versions of the tracker, depending on which libraries are installed. Two of the versions rely on OpenCV toolbox, where the first uses the mexopencv functionality to get OpenCV commands into matlab, and the second uses C++ directly. The third version will automatically run if you do not have OpenCV installed. It just uses Matlab without OpenCV, but instead needs the Matlab Vision Toolbox installed.  If you do not have the vision toolbox, you could install mexopencv and OpenCV and compile the xyTracker. It then automatically switches to the OpenCV commands and should not need the Vision Toolbox anymore. 

If you have problems, please let me know.  The xyTracker is still in the test-phase and I would appreciate any bug reports.

Best,
Malte

**Comment by maljoras** [comment]
Hi:
I updated the readme, where indeed the required Vision Toolbox was not mentioned. 

Thanks!
Best,
Malte

**Comment by maljoras** [comment]
In the actual version, vision toolbox is not required anymore. Other toolboxes shouldn't be necessary either. Please try to install the openCV/Mex version as described in the instructions on Windows/Linux
