### ISSUE TITLE
Can not install!

### ISSUE THREAD

**Issue by Zhaojian123** [maljoras/xyTracker#12]
Hi, 
    I do not know how to install xytracker based on Matlab 2013a only. I just download the fishtracker, and then add them to the path. But when I want to run "fish.Tracker.runTest();", the warning occured as : 
Error using fish.Tracker.runTest (line 423)
Please set PATHTOVIDEO to dowloaded video file available at
"http://www.cajal.csic.es/files/gpolavieja/5Zebrafish_nocover_22min.avi" or put the downloaded avi-file
into the "+fish/../data" directory.

Actually, I can not find the directory  "+fish/../data" ?

Then, when I want to run "ft = fish.Tracker([]);", the warning occured as :
Error using fish.Tracker/setupSystemObjects (line 814)
Please compile the code. Consult the Readme. ("make clean;make" on linux)

Error in fish.Tracker (line 3102) 
      self.setupSystemObjects(vid); % will call setOpts

I am confused.
Looking forward to your help!

**Comment by maljoras** [comment]
Hi: 
1) Please use the latest versiokn
2) cpp files need to be compiled 
3) The code is usable only for Matlab 2014b (and above) because the Vision toolbox is used
4) Code is optimized for linux so far
5) Under linux install openCV and mexopencv project

**Comment by maljoras** [comment]
Hi:

in the new version (v0.5.1), xyTracker can also be compiled and run in real-time on windows. Please refer to the readme for installation instructions.
